import image from "../assets/logo1.png";

export const foodsArray = [
  {
    id: 1,
    name: "Hamburger & Fries",
    description: "Classic beef cheeseburger served with crispy fries",
    price: 2500,
    inStock: true,
    quantity: 30,
    image: image,
  },
  {
    id: 2,
    name: "Fried Chicken",
    description: "Southern-style crispy fried chicken pieces",
    price: 3000,
    inStock: false,
    quantity: 0,
    image: image,
  },
  {
    id: 3,
    name: "Mac & Cheese",
    description: "Baked macaroni in creamy cheddar cheese sauce",
    price: 1800,
    inStock: true,
    quantity: 25,
    image: image,
  },
  {
    id: 4,
    name: "Clam Chowder",
    description: "Rich New England clam stew with potatoes & onions",
    price: 2600,
    inStock: true,
    quantity: 12,
    image: image,
  },
  {
    id: 5,
    name: "Buffalo Wings",
    description: "Spicy chicken wings served with blue cheese dip",
    price: 2000,
    inStock: false,
    quantity: 0,
    image: image,
  },
  {
    id: 6,
    name: "BBQ Ribs",
    description: "Slow-cooked pork ribs with sweet-tangy sauce",
    price: 5000,
    inStock: true,
    quantity: 8,
    image: image,
  },
  {
    id: 7,
    name: "Philly Cheesesteak",
    description: "Thin-sliced beef, onion & melted cheese in a hoagie roll",
    price: 2800,
    inStock: true,
    quantity: 15,
    image: image,
  },
  {
    id: 8,
    name: "Apple Pie",
    description: "Classic spiced apple pie slice served warm",
    price: 1500,
    inStock: false,
    quantity: 0,
    image: image,
  },
  {
    id: 9,
    name: "Chicken Pot Pie",
    description: "Savory pie with chicken, veggies and creamy sauce",
    price: 2700,
    inStock: true,
    quantity: 18,
    image: image,
  },
  {
    id: 10,
    name: "Grilled Cheese Sandwich",
    description: "Golden buttered toast melted with cheddar cheese",
    price: 1600,
    inStock: true,
    quantity: 22,
    image: image,
  },
  {
    id: 11,
    name: "Mashed Potatoes & Gravy",
    description: "Creamy mashed potatoes topped with rich gravy",
    price: 1400,
    inStock: false,
    quantity: 0,
    image: image,
  },
  {
    id: 12,
    name: "Cornbread",
    description: "Sweet Southern-style cornbread with golden crust",
    price: 1000,
    inStock: true,
    quantity: 25,
    image: image,
  },
  {
    id: 13,
    name: "Gumbo",
    description: "Creole stew with sausage, seafood & rice",
    price: 3600,
    inStock: true,
    quantity: 14,
    image: image,
  },
  {
    id: 14,
    name: "Jambalaya",
    description: "Creole rice with sausage, seafood & chicken",
    price: 3500,
    inStock: false,
    quantity: 0,
    image: image,
  },
  {
    id: 15,
    name: "Poutine",
    description: "Fries topped with cheese curds and gravy",
    price: 2300,
    inStock: true,
    quantity: 20,
    image: image,
  },
  {
    id: 16,
    name: "Tater Tots",
    description: "Crispy deep-fried potato tots, classic snack",
    price: 800,
    inStock: true,
    quantity: 35,
    image: image,
  },
  {
    id: 17,
    name: "Eggs Benedict",
    description: "Poached eggs on English muffins with hollandaise",
    price: 2200,
    inStock: true,
    quantity: 12,
    image: image,
  },
  {
    id: 18,
    name: "Chicken Divan",
    description: "Cheesy chicken and broccoli casserole (NY classic)",
    price: 2900,
    inStock: false,
    quantity: 0,
    image: image,
  },
  {
    id: 19,
    name: "American Chop Suey",
    description: "New England-style macaroni and beef tomato casserole",
    price: 2000,
    inStock: true,
    quantity: 18,
    image: image,
  },
  {
    id: 20,
    name: "Clams Casino",
    description: "Baked littleneck clams with bacon, breadcrumbs & peppers",
    price: 3300,
    inStock: true,
    quantity: 10,
    image: image,
  },
];
